//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAppsCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Component()
        {
            this.ComponentMaterialPreparationProcesses = new HashSet<ComponentMaterialPreparationProcess>();
            this.MemoComponents = new HashSet<MemoComponent>();
            this.ProductCompositions = new HashSet<ProductComposition>();
        }
    
        public int ID { get; set; }
        public string PartNumber { get; set; }
        public string PartName { get; set; }
        public int MaterialID { get; set; }
        public decimal Long { get; set; }
        public decimal Width { get; set; }
        public decimal Thickness { get; set; }
        public decimal OuterDiameter { get; set; }
        public decimal InnerDiameter { get; set; }
        public bool IsInHouse { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentMaterialPreparationProcess> ComponentMaterialPreparationProcesses { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemoComponent> MemoComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComposition> ProductCompositions { get; set; }
    }
}
