//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAppsCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentsTemp
    {
        public int ID { get; set; }
        public string ProductPartNumber { get; set; }
        public string ComponentPartNumber { get; set; }
        public string PartName { get; set; }
        public int Qty { get; set; }
        public string Bahan { get; set; }
        public decimal Long { get; set; }
        public decimal Width { get; set; }
        public decimal Thickness { get; set; }
        public decimal OuterDiameter { get; set; }
        public decimal InnerDiameter { get; set; }
        public decimal BS1 { get; set; }
        public decimal SGC2 { get; set; }
        public decimal ET3 { get; set; }
        public decimal PLM4 { get; set; }
        public decimal HGC5 { get; set; }
        public decimal AGC6 { get; set; }
        public decimal BPB7 { get; set; }
        public decimal RB8 { get; set; }
        public decimal RD9 { get; set; }
        public decimal TD10 { get; set; }
        public decimal HB11 { get; set; }
        public decimal GL12 { get; set; }
        public decimal GR13 { get; set; }
        public decimal BVL14 { get; set; }
        public decimal LB15 { get; set; }
        public decimal UML16 { get; set; }
        public decimal MHTotalPB { get; set; }
        public bool IsComponentExist { get; set; }
        public bool IsProductExist { get; set; }
        public bool IsInsertToPCom { get; set; }
        public bool IsInsertToCMPP { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
