//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAppsCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataZemesFail
    {
        public int ID { get; set; }
        public string ProNo { get; set; }
        public string Material { get; set; }
        public string MATGROUP { get; set; }
        public string MATDESC { get; set; }
        public string SerialNumber { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
