//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAppsCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessActivity
    {
        public int ID { get; set; }
        public int ProcessAssignID { get; set; }
        public int Status { get; set; }
        public Nullable<int> ReasonPauseID { get; set; }
        public System.DateTime ActivityDateTime { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual ProcessAssign ProcessAssign { get; set; }
        public virtual ReasonPause ReasonPause { get; set; }
    }
}
