//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAppsCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComposition
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int ComponentID { get; set; }
        public int Quantity { get; set; }
        public bool IsDefaultComponent { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Products Products { get; set; }
    }
}
