//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAppsCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSalesOrder
    {
        public int ID { get; set; }
        public int PROID { get; set; }
        public int SalesOrderID { get; set; }
        public int PROQuantityUsed { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual PRO PRO { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
