//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAppsCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.Processes = new HashSet<Process>();
            this.ShopFloorSchedules = new HashSet<ShopFloorSchedule>();
        }
    
        public int ID { get; set; }
        public int PROID { get; set; }
        public Nullable<int> SalesOrderID { get; set; }
        public int ProductID { get; set; }
        public string ChasisNumber { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<int> MPSID { get; set; }
        public Nullable<System.DateTime> MPSDueDate { get; set; }
        public Nullable<System.DateTime> SFSDueDate { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public Nullable<int> ActualDeliveryWeekID { get; set; }
        public bool IsHold { get; set; }
        public Nullable<int> ReasonIssueID { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual MasterPlanSchedule MasterPlanSchedule { get; set; }
        public virtual PRO PRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process> Processes { get; set; }
        public virtual Products Product { get; set; }
        public virtual ReasonIssue ReasonIssue { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopFloorSchedule> ShopFloorSchedules { get; set; }
    }
}
