//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAppsCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProductProcessDailySchedule
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int MasterProcessID { get; set; }
        public int ProcessOrder { get; set; }
        public int Day { get; set; }
        public string MasterProcessName { get; set; }
        public int ProcessGroupID { get; set; }
    }
}
